---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starboard-security-operator
  namespace: starboard
imagePullSecrets:
  - name: starboard-registry-credentials
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: starboard-security-operator
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
      - "pods/log"
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
  - apiGroups:
      - aquasecurity.github.io
    resources:
      - vulnerabilities
    verbs:
      - get
      - list
      - watch
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: starboard-security-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: starboard-security-operator
subjects:
  - kind: ServiceAccount
    name: starboard-security-operator
    namespace: starboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starboard-security-operator
  namespace: starboard
  labels:
    app: starboard-security-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: starboard-security-operator
  template:
    metadata:
      labels:
        app: starboard-security-operator
    spec:
      serviceAccountName: starboard-security-operator
      securityContext:
        runAsNonRoot: true
        runAsUser: 10000
        fsGroup: 10000
      initContainers:
        - name: scannercli
          image: aquasec.azurecr.io/scanner:4.6
          imagePullPolicy: IfNotPresent
          args: ["version"]
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
      containers:
        - name: operator
          image: aquasec/starboard-security-operator:dev
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: false
            readOnlyRootFilesystem: true
          env:
            - name: OPERATOR_SCANNER_AQUA_CSP_VERSION
              value: "4.6"
            - name: OPERATOR_SCANNER_AQUA_REGISTRY_SERVER
              value: aquasec.azurecr.io
