---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: starboard-operator
  namespace: starboard-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: starboard-operator
subjects:
  - kind: ServiceAccount
    name: starboard-operator
    namespace: starboard-operator
